### ISSUE TITLE
About the file /instances_train2017_seen_2_oriorder_cat_info.json

### ISSUE THREAD

**Issue by ZWH0413** [mala-lab/SIC-CADS#4]
I tried to retrain the MLR moudle and not found the file `datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json` 

Do I miss something needed? Thanks.

**Comment by wl2002uestc** [comment]
You can try this command: `python tools/get_lvis_cat_info.py --ann datasets/coco/zero-shot/instances_train2017_seen_2_oriort.json`

**Comment by ZWH0413** [comment]
Thanks！
